define(["module"],function(module){
	"use strict";
	module.exports={
		"catchError":true,
		"enforceDefine":true,
		"waitSeconds":0,
		"baseUrl":"/kwetl/src",
		"paths":{
			"kwe.rebase":"lib/kwe/rebase/index",
			"text":"lib/requirejs/require.text",
			"jquery":"lib/jquery/jquery.3.5.1",
			"jquery-private":"lib/jquery/jquery-private",
			"css":"lib/requirecss/css",
		},
		"packages":[],
		"config":{
			"text":{}
		},
		"map":{
			"*":{},
			"jquery-private":{"jquery":"jquery"},
		},
		"shim":{
		},
		"deps":[]
	};
	require.config(module.exports);
});
